### ISSUE TITLE
Suggestion: Full-sized keyboards!

### ISSUE THREAD

**Issue by benkates** [sharlagelfand/ggkeyboard#4]
First off, this is AWESOME, thank you for building this. I started adding keys for the numpad but realized halfway through that a height param isn't in place, so I don't think it'd be possible to do a 2x tall key right now, is that the case? Here's what I was working on.

```r
library(ggkeyboard)
library(tidyverse)

test <- tibble::tribble(
  ~key, ~row, ~width, ~number, ~key_label, ~key_type,
  NA, 5, .25, 20, NA,NA,
  "NumLock", 5, 1, 21, "Num\nLock","modifier",
  "/", 5, 1, 22, "/","modifier",
  "*", 5, 1, 23, "*","modifier",
  "-", 5, 1, 24, "-","modifier",
  
  NA, 4, .25, 20, NA,NA,
  "7side", 4, 1, 21, "7","alphanumeric",
  "8side", 4, 1, 22, "8","alphanumeric",
  "9side", 4, 1, 23, "9","alphanumeric",
  "+side", 4, 1, 24, "+","modifier",
  
  NA, 3, .25, 20, NA,NA,
  NA, 3, 1, 21, NA,NA,
  NA, 3, 1, 22, NA,NA,
  NA, 3, 1, 23, NA,NA,
  NA, 3, .25, 20, NA,NA,
  "4side", 3, 1, 24, "4","alphanumeric",
  "5side", 3, 1, 25, "5","alphanumeric",
  "6side", 3, 1, 26, "6","alphanumeric",
  
  NA, 2, .25, 20, NA,NA,
  NA, 2, 1, 21, NA,NA,
  "1side", 2, 1, 22, "1","alphanumeric",
  "2side", 2, 1, 23, "2","alphanumeric",
  "3side", 2, 1, 24, "3","alphanumeric",
  "Enterside", 2, 1, 24, "Enter","modifier",
  
  NA, 1, .25, 20, NA,NA,
  "0side", 1, 2, 22, "0","alphanumeric",
  ".side", 1, 1, 23, ".","alphanumeric"
)

tkl_mod <- ggkeyboard::tkl %>% 
  dplyr::add_row(test)

ggkeyboard(data = tkl_mod)
```

![image](https://user-images.githubusercontent.com/17264005/88947722-ee00a580-d25e-11ea-8718-8bc12f8fc04a.png)

**Comment by sharlagelfand** [comment]
thank you! and thanks for putting this together - you're 100% right, it's assuming that all keys are the same height right now.

I have plans to include data sets for full and 60% layouts, at the very least, so thank you for doing a big chunk of the work on the full layout for me 😂 i'll take a look over the next couple days re: adding a height parameter in throughout

**Comment by benkates** [comment]
No problem! Glad to know I wasn't missing something, sounds great.

**Comment by sharlagelfand** [comment]
"next couple days" more like "next couple hours". Thanks for your start on this, made things go a lot quicker!

``` r
library(ggkeyboard)

ggkeyboard(full)
```

![](https://raw.githubusercontent.com/sharlagelfand/ggkeyboard/main/man/figures/README-full-1.png)
