### ISSUE TITLE
Change key mapping

### ISSUE THREAD

**Issue by statzhero** [sharlagelfand/ggkeyboard#6]
Question: how would you recommend changing the keyboard's key mapping? 

Thanks!

**Comment by sharlagelfand** [comment]
Can you be more specific re: what you're trying to do? Change how keys are labelled? Where they appear?

**Comment by statzhero** [comment]
For example, instead of key “a” display “b”. Or use a different layout altogether such as _Colemak_. Happy to go to the source if you point me there.

**Comment by sharlagelfand** [comment]
It's probably helpful to look at the changes made in PR #5, since that adds a new layout so you can see where things are changed.

In general with R packages, the raw data and scripts to process them to make package datasets (which is what the keyboard layouts are) live in the `data-raw/` folder.
